name: Build and Push Docker Images to Dockerhub
on:
  push:
    branches:
      - master  # Change this to your main branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push API1 Docker Image
      working-directory: .
      run: |
        docker build -t matevos1998/shopium:giftcardapi . -f DockerfileGiftCard
        docker push matevos1998/shopium:giftcardapi
